services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_CONTRACT_ADDRESS: ${VITE_CONTRACT_ADDRESS}
        VITE_RPC_URL: ${VITE_RPC_URL}
    container_name: ajo-frontend
    restart: always
    ports:
      - "8081:80"
    env_file:
      - ./.env